## Linear Algebra with numpy

In [1]:
import numpy as np

In [2]:
A = np.matrix([[5, 6, 2],
               [4, 7, 9],
               [0, 3, 12]])

In [3]:
A

matrix([[ 5,  6,  2],
        [ 4,  7,  9],
        [ 0,  3, 12]])

In [4]:
type(A)

numpy.matrix

In [5]:
B = np.array([[14, -2, 12], [4, 4, 5], [5, 2, 1]])

B

array([[14, -2, 12],
       [ 4,  4,  5],
       [ 5,  2,  1]])

In [6]:
type(B)

numpy.ndarray

### Identity matrix

In [7]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5)  # np.eye() is an alias to np.identity()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Transpose

In [10]:
B.T

array([[14,  4,  5],
       [-2,  4,  2],
       [12,  5,  1]])

In [11]:
A.T

matrix([[ 5,  4,  0],
        [ 6,  7,  3],
        [ 2,  9, 12]])

### Addition

In [12]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 14],
        [ 5,  5, 13]])

In [13]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,   4],
        [ -5,   1,  11]])

### Scalar multiplication

In [14]:
A

matrix([[ 5,  6,  2],
        [ 4,  7,  9],
        [ 0,  3, 12]])

In [15]:
k = 3.5

k * A

matrix([[17.5, 21. ,  7. ],
        [14. , 24.5, 31.5],
        [ 0. , 10.5, 42. ]])

In [16]:
B

array([[14, -2, 12],
       [ 4,  4,  5],
       [ 5,  2,  1]])

In [17]:
B/k  # if k != 0

array([[ 4.        , -0.57142857,  3.42857143],
       [ 1.14285714,  1.14285714,  1.42857143],
       [ 1.42857143,  0.57142857,  0.28571429]])

### Element wise multiplication (Hadamard product)

In [18]:
np.multiply(A, B)   # element-wise multiplication

matrix([[ 70, -12,  24],
        [ 16,  28,  45],
        [  0,   6,  12]])

In [19]:
A

matrix([[ 5,  6,  2],
        [ 4,  7,  9],
        [ 0,  3, 12]])

In [20]:
B

array([[14, -2, 12],
       [ 4,  4,  5],
       [ 5,  2,  1]])

In [ ]:
A * B   # this is not element-wise multiplication (normal matrix multiplication)

matrix([[104,  18,  92],
        [129,  38,  92],
        [ 72,  36,  27]])

### Vector - Matrix multiplication

In [22]:
M = np.matrix([[2, 3, 0, -1],[6, 7, -2, 1]])

M.shape

(2, 4)

In [23]:
M

matrix([[ 2,  3,  0, -1],
        [ 6,  7, -2,  1]])

In [24]:
v = np.array([0.5, 1, -1, 0])

In [25]:
v

array([ 0.5,  1. , -1. ,  0. ])

In [26]:
np.dot(M, v)

matrix([[ 4., 12.]])

In [ ]:
M @ v   # @ is the symbol we can use for matrix multiplication

matrix([[ 4., 12.]])

In [28]:
w = np.array([1, 2, 3, 4])

np.dot(v, w)

np.float64(-0.5)

### Determinant value of a square matrix

In [29]:
mat = np.matrix([[2, 4, 5], [3, 2, 1], [1, 5, -2]])

print(mat)

[[ 2  4  5]
 [ 3  2  1]
 [ 1  5 -2]]


In [30]:
np.linalg.det(mat)

np.float64(74.99999999999997)

### Eigen values and Eigen vectors

In [31]:
A = np.matrix([[4, -1],[2, 1]])

In [33]:
A

matrix([[ 4, -1],
        [ 2,  1]])

In [32]:
np.linalg.det(A)

np.float64(6.0)

In [34]:
np.linalg.eig(A)

EigResult(eigenvalues=array([3., 2.]), eigenvectors=matrix([[0.70710678, 0.4472136 ],
        [0.70710678, 0.89442719]]))

In [35]:
v, B = np.linalg.eig(A)

In [36]:
v

array([3., 2.])

In [37]:
B

matrix([[0.70710678, 0.4472136 ],
        [0.70710678, 0.89442719]])

In [40]:
mat

matrix([[ 2,  4,  5],
        [ 3,  2,  1],
        [ 1,  5, -2]])

In [38]:
v, B = np.linalg.eig(mat)

In [39]:
print(v)

[ 7.12577876+0.j         -2.56288938+1.98916149j -2.56288938-1.98916149j]


In [41]:
print(B)

[[ 0.76844087+0.j         -0.70202669+0.j         -0.70202669-0.j        ]
 [ 0.52197261+0.j          0.27371705+0.2189159j   0.27371705-0.2189159j ]
 [ 0.37019349+0.j          0.42168038-0.45442161j  0.42168038+0.45442161j]]


### Matix - Matrix multiplication

In [42]:
A = np.matrix([[2, 3, 4, 5], [6, 7, 8, 9], [1, -1, 2, 3]])

B = np.matrix([[1, 3], [-1, 0], [0, -2], [2, 1]])

In [43]:
A

matrix([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [ 1, -1,  2,  3]])

In [44]:
B

matrix([[ 1,  3],
        [-1,  0],
        [ 0, -2],
        [ 2,  1]])

In [ ]:
np.dot(A, B)   # A @ B

matrix([[ 9,  3],
        [17, 11],
        [ 8,  2]])

In [46]:
np.dot(B, A)

ValueError: shapes (4,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

### Inverse of a matrix

In [47]:
A = np.matrix([[2, 3, 4], [6, 7, 8], [1, -1, 2]])

A

matrix([[ 2,  3,  4],
        [ 6,  7,  8],
        [ 1, -1,  2]])

In [48]:
np.linalg.det(A)

np.float64(-20.000000000000007)

In [49]:
B = np.linalg.inv(A)  # or B = A.I

In [50]:
B

matrix([[-1.1 ,  0.5 ,  0.2 ],
        [ 0.2 , -0.  , -0.4 ],
        [ 0.65, -0.25,  0.2 ]])

In [51]:
np.round(np.dot(A, B),3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
np.round(np.dot(B, A), 3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [53]:
C = np.matrix([[1,2,3], [4,5,6], [7,8,9]])

C

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
np.linalg.det(C)

np.float64(0.0)

In [55]:
C.I

LinAlgError: Singular matrix

In [56]:
np.linalg.eig(C)

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), eigenvectors=matrix([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))